spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.user=${DB_MIGRATOR_USERNAME}
spring.flyway.password=${DB_MIGRATOR_PASSWORD}

logging.structured.format.console=ecs
